### This is a test file that assumes that you have access to the data base. To see and edit  
### a user's tasks  you will need correct credentials from the database. 
### Paste correct credentials in the variables validEmail and validPass from DB.

### You can create a new user,  but since it won't have tasks assciated, you won't
### be able to use its access token to see or edit their tasks.
### edit new user credentials in the variables newUserEmail, newUserPass and newUserFullName

@baseUrl = http://localhost:5005
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5YmY1MDliLTAxYzUtNDFkYy1iMWVmLWY5ODRlYjU1MWM4ZCIsImVtYWlsIjoiZXN0ZXJfdmFsbGFkYXJlc2FiZXl0YUBnbWFpbC5jb20iLCJpYXQiOjE3NTM4NjU1MTEsImV4cCI6MTc1Mzg2OTExMX0.YX2keky9VVsku1sht16hEsb07cP-UkAON7KkynW3MYA
@taskId = 3b05d521-501a-4973-a12e-73f210fbaf2d
@validEmail = "ester_valladaresabeyta@gmail.com"
@validPass = "ZGygwZJWpjkpH5_"
@newUserEmail =  "testNewUser0@gmail.com"
@newUserPass = "@ValidNewPassword1234"
@newUserFullName = "John Doe"

### Canary
GET {{baseUrl}}

### Failed Login: invalid mail adress

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "foo",
  "pass": "bar"
}

### Failed Login: invalid password

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": {{validEmail}},
  "pass": ""
}

### Failed Login: wrong dto

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "pass": ""
}

### Successful Login: Get access token
### get the token from response and paste it 
### at the top of the file variable

POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": {{validEmail}},
  "pass": {{validPass}}
}

### Successful Get user's tasks
### Get a task Id and paste it a the top of the 
### file variable

GET {{baseUrl}}/tasks
Authorization: Bearer {{token}}
Content-Type: application/json

### Get user's task unauthorized

GET {{baseUrl}}/tasks
Authorization: Bearer notAToken
Content-Type: application/json

### Successful See a user's task

GET {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer {{token}}
Content-Type: application/json

### See a user's: task unauthorized

GET {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer notAtoken
Content-Type: application/json

### See a user's: task not found

GET {{baseUrl}}/tasks/1234
Authorization: Bearer {{token}}
Content-Type: application/json

### Successful Edit a user's task 
PUT {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "This is a test",
  "description": "This is a test to update a task that should be authorized by the backend"
}

### Edit a user's task: bad input
PUT {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "This is test",
  "dueDate": "2025-01-10",
  "description": "This is a test to update a task that should be authorized by the backend"
}

### Edit a user's task: wrong dto
PUT {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Alejandro",
  "age": 13,
  "course": "2B"
}

### Edit a user's task: unauthorized
PUT {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer notAToken
Content-Type: application/json

{
  "title": "This is a updated  task",
  "description": "This is a test to update a task that should NOT be authorized by the backend"
}

### Edit a user's task: not found
PUT {{baseUrl}}/tasks/notAnId
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "This is a updated  task",
  "description": "This is a test to update a task that should be authorized by the backend"
}

### Create a new user: too simple password
POST {{baseUrl}}/users/create
Content-Type: application/json

{
  "email": {{newUserEmail}},
  "pass": "1234",
  "fullname": {{newUserFullName}}
}

### Create a new user: no dto fullname

POST {{baseUrl}}/users/create
Content-Type: application/json

{
  "email": {{newUserEmail}},
  "pass": {{newUserPass}}
}

### Create a new user: bad dto email
POST {{baseUrl}}/users/create
Content-Type: application/json

{
  "email": "notanemail",
  "pass": {{newUserPass}},
  "fullname": {{newUserFullName}}
}

### Successful Create a new user
POST {{baseUrl}}/users/create
Content-Type: application/json

{
  "email": {{newUserEmail}},
  "pass": {{newUserPass}},
  "fullname": {{newUserFullName}}
}

### Create a new user: repeated email
POST {{baseUrl}}/users/create
Content-Type: application/json

{
  "email": {{newUserEmail}},
  "pass": {{newUserPass}},
  "fullname": {{newUserFullName}}
}

### Successful login newUser
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": {{newUserEmail}},
  "pass": {{newUserPass}}
}




